apiVersion: apps/v1
kind: Deployment
metadata: { name: shadow-api, namespace: bookstore-api }
spec:
  replicas: 1
  selector: { matchLabels: { app: shadow } }
  template:
    metadata: { labels: { app: shadow } }   # no zta.* labels
    spec:
      containers: [{ name: c, image: nginx:1.27-alpine }]
